CREATE TABLE sri (
  sri_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  scene_id INTEGER NOT NULL,
  category1 INTEGER NOT NULL,
  category2 INTEGER,
  FOREIGN KEY (category1) REFERENCES category(category_id) ON DELETE CASCADE
) ENGINE=INNODB;

