CREATE TABLE HAD (
  srvkey VARCHAR(40) NOT NULL PRIMARY KEY,
  student VARCHAR(80),
  now VARCHAR(80),
  HAD_1 INTEGER,
  HAD_2 INTEGER,
  HAD_3 INTEGER,
  HAD_4 INTEGER,
  HAD_5 INTEGER,
  HAD_6 INTEGER,
  HAD_7 INTEGER,
  HAD_8 INTEGER,
  HAD_9 INTEGER,
  HAD_10 INTEGER,
  HAD_11 INTEGER,
  HAD_12 INTEGER,
  HAD_13 INTEGER,
  HAD_14 INTEGER,
  HAD_15 INTEGER
);

